# core/json_io.py

"""JSON loading, saving helpers, and marker conversion for FAST data."""

import json
import re
from pathlib import Path


# FAST unspecified input marker.
nan = float("nan")

# Default example case directory and schema file names. InputAircraft.json is
# the single required run input.
DEFAULT_INPUT_DIR = Path("examples/CeRAS")
SCHEMA_DIR = Path("schema")
AIRCRAFT_JSON_PATH = Path("InputAircraft.json")
INPUT_AIRCRAFT_SCHEMA_JSON_PATH = Path("InputAircraftSchema.json")
OUTPUT_AIRCRAFT_SCHEMA_JSON_PATH = Path("OutputAircraftSchema.json")


JsonValidationError = ValueError


def print_result(result):
    """Print a cleaned FAST command-window log.

    Inputs:
        result: Dictionary returned by FAST_Python_Wrapper(), optionally
            containing a MATLAB command-window log under the "log" key.

    Outputs:
        None. The cleaned log is printed only when it is non-empty.

    Side effects:
        Writes to standard output for interactive runs.
    """

    # FAST logs can contain MATLAB backspace characters and HTML links from
    # command-window warnings. Strip those so terminal output is readable.
    log = result.get("log", "")
    log = log.replace("\x08", "")
    log = re.sub(r"<a\b[^>]*>", "", log)
    log = log.replace("</a>", "")
    log = log.strip()

    if log:
        print()
        print("FAST log:")
        print(log)


def build_json_data(value):
    """Return a JSON-safe copy of FAST data.

    Inputs:
        value: Python FAST data that may include MATLAB marker dictionaries,
            MATLAB Engine arrays, NaN markers, nested dictionaries, or lists.

    Outputs:
        A JSON-serializable structure preserving field names and MATLAB source
        expressions. NaN and infinities are written as strings because standard
        JSON has no portable non-finite number literals.

    Assumptions:
        Input files can be rehydrated by load_json_data(). Unsupported
        MATLAB/Python objects fall back to a stable string representation so
        output JSON does not contain runtime-specific marker objects.
    """

    if isinstance(value, dict):
        keys = set(value)

        if keys == {"_matlab_expression"}:
            return value

        if keys == {"_matlab_row"}:
            return {
                "_matlab_row": build_json_data(value["_matlab_row"]),
            }

        return {
            key: build_json_data(item)
            for key, item in value.items()
        }

    if isinstance(value, list) or isinstance(value, tuple):
        return [build_json_data(item) for item in value]

    if isinstance(value, float):
        if value != value:
            return "NaN"

        if value == float("inf"):
            return "Inf"

        if value == -float("inf"):
            return "-Inf"

    module_name = type(value).__module__

    if (
        (module_name == "matlab" or module_name.startswith("matlab."))
        and hasattr(value, "__iter__")
    ):
        return [build_json_data(item) for item in value]

    if value is None or isinstance(value, str):
        return value

    if isinstance(value, bool) or isinstance(value, int) or isinstance(value, float):
        return value

    return re.sub(r" at 0x[0-9A-Fa-f]+(?=>)", "", str(value))


def load_json_data(value):
    """Convert JSON FAST input data back into FAST-ready Python data.

    Inputs:
        value: Data loaded from InputAircraft.json.

    Outputs:
        Python data accepted by FAST_Python_Wrapper(), including restored MATLAB marker
        dictionaries and NaN values.

    Assumptions:
        The JSON files use the marker objects generated by build_json_data().
        Plain string "NaN" and JSON null are treated as the FAST unspecified
        input marker.
    """

    if isinstance(value, dict):
        if set(value.keys()) == {"_matlab_expression"}:
            return value

        if set(value.keys()) == {"_matlab_row"}:
            return {
                "_matlab_row": load_json_data(value["_matlab_row"]),
            }

        return {
            key: load_json_data(item)
            for key, item in value.items()
        }

    if isinstance(value, list):
        return [load_json_data(item) for item in value]

    if value == "NaN":
        return nan

    if value == "Inf":
        return float("inf")

    if value == "-Inf":
        return -float("inf")

    if value is None:
        return nan

    return value


def read_raw_json_file(path):
    """Parse a JSON file and report file-specific syntax errors.

    Inputs:
        path: JSON file path to read.

    Outputs:
        Data returned by json.loads().

    Side effects:
        None.
    """

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise JsonValidationError(
            f"{path} is not valid JSON: {error.msg} at line "
            f"{error.lineno}, column {error.colno}."
        ) from error


def require_json_object(value, path):
    """Return value when it is a JSON object, otherwise fail.

    Inputs:
        value: Parsed JSON value.
        path: Human-readable location used in the error message.

    Outputs:
        The original value when it is a dictionary.

    Assumptions:
        FAST aircraft, mission, and OutputAircraft files are object roots.
    """

    if not isinstance(value, dict):
        raise JsonValidationError(f"{path} must be a JSON object.")

    return value


def get_json_path(data, keys, file_name):
    """Read a required nested JSON field.

    Inputs:
        data: Parsed JSON object.
        keys: List of nested field names.
        file_name: File label used in validation errors.

    Outputs:
        The nested value.
    """

    current = data
    walked = []

    for key in keys:
        walked.append(key)

        if not isinstance(current, dict) or key not in current:
            joined = ".".join(walked)
            raise JsonValidationError(f"{file_name} is missing required field {joined}.")

        current = current[key]

    return current


def is_json_number(value):
    """Return True for JSON numeric values that are not booleans."""

    return (isinstance(value, int) or isinstance(value, float)) and not isinstance(
        value,
        bool,
    )
